[package]
name = "xdid-method-key"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[features]
default = [
  "ed25519",
  "x25519",
  "secp256k1",
  "bls12381",
  "p256",
  "p384",
  "p521",
  "rsa",
]
ed25519 = ["dep:ring"]
x25519 = []
secp256k1 = []
bls12381 = []
p256 = []
p384 = []
p521 = []
rsa = []

[dependencies]
multibase = "0.9.1"
ring = { version = "0.17.8", optional = true }
unsigned-varint = { version = "0.8.0" }
xdid-core = { path = "../xdid-core" }
